### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by thestr4ng3r** [Phillip-May/snes-homebrew#1]
Please clarify under which license the code in this repository may be used.

**Comment by Phillip-May** [comment]
It's under the MIT license, it won't do you too much good though because all the c code relies on wdc's c compiler and assembler which are proprietary.

**Comment by thestr4ng3r** [comment]
Thanks for the update! I'm mostly interested in using the examples as test binaries as part of https://github.com/rizinorg/rizin-testbins so that should be fine, but I will check in detail the wdc tools before.
